export const imagesSources = {
  all: [
    {
      imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleAnalytics.png',
    },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleData.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleTag.png' },
    {
      imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoBigComm.png',
      urlTo: '/bigcommerce',
    },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoKibo.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoOracleATG.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoRev.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoShopify.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoEon.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoMagicLeap.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoUnitynew.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoPTC.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoFacebook.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleAds.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoKlayvio.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoSocialCom.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoAWS.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoAzure.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleCloud.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoOracleEndeca.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoOracleMax.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogo6Sigma.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoABTasty.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoContentSquare.png' },
  ],
  data: [
    {
      imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleAnalytics.png',
    },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleData.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleTag.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoOracleEndeca.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoContentSquare.png' },
  ],
  ecom: [
    {
      imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoBigComm.png',
      urlTo: '/bigcommerce',
    },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoKibo.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoOracleATG.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoRev.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoShopify.png' },
  ],
  emergTech: [
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoEon.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoMagicLeap.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoPTC.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoUnitynew.png' },
  ],
  marketing: [
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoFacebook.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleAds.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoKlayvio.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoSocialCom.png' },
  ],
  tech: [
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoAWS.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoAzure.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoGoogleCloud.png' },
  ],
  testing: [
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoKibo.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoOracleMax.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogo6Sigma.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoABTasty.png' },
    { imgUrl: 'https://storage.googleapis.com/peakactivity-site-assets/partners/logos/partnersLogoContentSquare.png' },
  ],
}
